import logging
from typing import Optional, List
from models import SourceDocument

logger = logging.getLogger(__name__)


class ResponseFormatter:
    """Format responses according to Vivli standards"""

    AI_DISCLAIMER = """ⓘ The information above was generated by an AI system. While reviewed for accuracy, AI can make mistakes. If this answer doesn't resolve your issue, please select "This did not help" to contact our support team."""

    def format_faq_response(
        self,
        answer: str,
        sources: List[SourceDocument],
        researcher_name: Optional[str] = None,
    ) -> str:
        """
        Format FAQ response with sources and disclaimer.

        Args:
            answer: Generated answer text
            sources: List of source documents
            researcher_name: Optional researcher name for greeting

        Returns:
            Formatted response string
        """
        greeting = f"Hi {researcher_name}," if researcher_name else "Hi there,"

        # Format sources
        source_text = ""
        if sources:
            source_text = f"\nSource: {sources[0].citation_url}" if sources[0].citation_url else ""

        formatted = f"""{greeting}

{answer}{source_text}

Was this helpful?
👍 [Yes, this helped]  |  👎 [No, this didn't help]

{self.AI_DISCLAIMER}"""

        return formatted

    def format_data_request_response(
        self,
        answer: str,
        request_id: str,
        current_stage: str,
        researcher_name: Optional[str] = None,
    ) -> str:
        """
        Format data request status response.

        Args:
            answer: Generated status update
            request_id: Data request ID
            current_stage: Current stage
            researcher_name: Optional researcher name

        Returns:
            Formatted response string
        """
        greeting = f"Hi {researcher_name}," if researcher_name else "Hi there,"

        formatted = f"""{greeting}

Your data request {request_id} is currently at the following stage: {current_stage}.

{answer}

If you have further questions, feel free to ask here.

{self.AI_DISCLAIMER}"""

        return formatted

    def format_hybrid_response(
        self,
        data_request_answer: str,
        faq_answer: str,
        request_id: str,
        current_stage: str,
        sources: List[SourceDocument],
        researcher_name: Optional[str] = None,
    ) -> str:
        """
        Format hybrid response (both data request + FAQ).

        Args:
            data_request_answer: Data request status answer
            faq_answer: FAQ answer
            request_id: Data request ID
            current_stage: Current stage
            sources: Source documents
            researcher_name: Optional researcher name

        Returns:
            Formatted response string
        """
        greeting = f"Hi {researcher_name}," if researcher_name else "Hi there,"

        source_text = ""
        if sources:
            source_text = (
                f"\nSource: {sources[0].citation_url}"
                if sources[0].citation_url
                else ""
            )

        formatted = f"""{greeting}

Regarding your data request {request_id}:

Status: {current_stage}
{data_request_answer}

Regarding your question:

{faq_answer}{source_text}

If you have further questions, feel free to ask here.

Was this helpful?
👍 [Yes, this helped]  |  👎 [No, this didn't help]

{self.AI_DISCLAIMER}"""

        return formatted

    def format_escalation_response(self) -> str:
        """
        Format escalation response.

        Returns:
            Formatted escalation message
        """
        formatted = f"""I'm sorry, but I couldn't find a reliable answer to your question in our knowledge base.

To make sure you receive the correct information, I've forwarded your question to a Vivli Administrator, who will review it and respond as soon as possible.

Thank you for your patience.

{self.AI_DISCLAIMER}"""

        return formatted

    def format_multiple_queries_response(
        self,
        answers: List[dict],  # [{"question": "...", "answer": "..."}]
        sources: List[SourceDocument],
        researcher_name: Optional[str] = None,
    ) -> str:
        """
        Format response for multiple questions.

        Args:
            answers: List of question-answer pairs
            sources: Source documents
            researcher_name: Optional researcher name

        Returns:
            Formatted response string
        """
        greeting = f"Hi {researcher_name}," if researcher_name else "Hi there,"

        # Format each answer
        questions_section = ""
        for i, qa in enumerate(answers, 1):
            questions_section += f"**Question {i}: {qa['question']}**\n{qa['answer']}\n\n"

        source_text = ""
        if sources:
            source_text = (
                f"\nSource: {sources[0].citation_url}"
                if sources[0].citation_url
                else ""
            )

        formatted = f"""{greeting}

I'll address each of your questions:

{questions_section}
If you need clarification on any of these answers, please let me know.{source_text}

Was this helpful?
👍 [Yes, this helped]  |  👎 [No, this didn't help]

{self.AI_DISCLAIMER}"""

        return formatted

    def format_error_response(self, error_message: str) -> str:
        """
        Format error response for user.

        Args:
            error_message: Error message to display

        Returns:
            Formatted error message
        """
        return f"I'm sorry, but I encountered an error: {error_message}. Please try again or contact support if the issue persists."
